{
    'name': "Elearning Features",
    'summary': """ """,
    'author': "Innona.do",
    'category': 'Website',
    'version': '17.0',
    'depends': [
        'contacts',
        'web',
        'documents',
        'website_slides',
        'website_sale_slides',
        'website_profile',
        'website_slides_forum',
        'website_form_validation',
        'website_event',
        'web_notify',
        'website_blog',
        'auth_signup',
        'survey',
        'portal',
        # 'website_rating',
        # 'payment_azul',
        'website_event_sale',
        'gamification',
    ],
    # always loaded
    'data': [

        'security/ir.model.access.csv',
        # 'data/website_data.xml',
        'data/mail_data.xml',
        'data/survey_data.xml',
        'data/slide_channel_tag_data.xml',
        'data/ir_config_parameter_data.xml',
        # 'views/assets.xml',
        'views/website_login_template.xml',
        'views/website_slides_templates_lesson_fullscreen.xml',
        'views/website_template_course.xml',
        'views/website_event_template.xml',
        'views/res_country_city_view.xml',
        'views/res_country_town_view.xml',
        'views/res_partner_view.xml',
        'views/res_users_view.xml',
        'views/suggest_product_views.xml',
        'views/slide_channel_view.xml',
        'views/cron_view.xml',
        'views/survey_templates.xml',
        'views/header_layout.xml',
        'views/auth_signup_login_templates.xml',
        'views/website_document_view.xml',
        'views/website_document_template.xml',
        'views/website_video_template.xml',
        'views/website_teachers_template.xml',
        'views/website_glosary_template.xml',
        'views/website_calculator_template.xml',
        'views/help_center_view.xml',
        'views/website_helpcenter_template.xml',
        'views/blog_social.xml',
        'views/popular_report_views.xml',
        'views/portal_template.xml',
        'views/web_layout.xml',
        'views/website_user_survey_template.xml',
        'views/website_slide_template_homepage.xml',
        'views/academia_desing.xml',
        'views/blog_view.xml',
        'views/import_user_view.xml',
        'views/survey_report_templates.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            # 'elearning_features/static/src/css/**/*',
            # 'elearning_features/static/src/js/**/*',
            # 'elearning_features/static/src/libs/**/*',
            # 'elearning_features/static/src/xml/**/*',
            'elearning_features/static/src/css/home.css',
            'elearning_features/static/src/css/website_profile.css',
            'elearning_features/static/src/js/profile.js',  #DNS_PROBE_FINISHED_NXDOMAIN "https://apip.deparenpar.edu.do/
            # 'elearning_features/static/src/css/app.css',
            'elearning_features/static/src/css/cal-generic.css',
            'elearning_features/static/src/css/calculadoras_personales.css',
            #'elearning_features/static/src/js/calculadoras_personales.js',
            'elearning_features/static/src/css/calculadoras_certificado.css',
            'elearning_features/static/src/css/calculadoras_meta_de_ahorro.css',
            #'elearning_features/static/src/css/app_for_desing.css',
            'elearning_features/static/src/css/blog_detalle.css',
            # #academia_assets_frontend
            '/elearning_features/static/src/css/impulsa.css',
            'elearning_features/static/src/css/perfiles.css',
            'elearning_features/static/src/css/chatbot.css',
            'elearning_features/static/src/css/carousel.css',
            'elearning_features/static/src/css/homepage.css',
            'elearning_features/static/src/css/header.css',
            'elearning_features/static/src/css/style_fonts.css',
            'elearning_features/static/src/js/calculadora_personales_header.js', #ok
            #'elearning_features/static/src/js/calculadoras_certificado.js',
            'elearning_features/static/src/js/calculadora_pension.js', #ok
            'elearning_features/static/src/js/calculadoras_fondo_emergencia.js', #ok
            #'elearning_features/static/src/js/calculadoras_metas.js',
            #'elearning_features/static/src/libs/vimeo_player.js',
            'elearning_features/static/src/js/slides_course_unfavorite.js', #ok
            'elearning_features/static/src/js/slides_course_fullscreen_player.js', #ok, probar en rpc??
            'elearning_features/static/src/js/blog_social.js',
            'elearning_features/static/src/js/help_center.js',
            'elearning_features/static/src/js/app.js',
            'elearning_features/static/src/js/calculadoras.js', #ok no dio problemas
            # 'elearning_features/static/src/libs/vimeo_player.js',
            # 'elearning_features/static/src/libs/vimeo_player.js',
            #'elearning_features/static/src/js/signup.js',
        ],
    },
    # 'qweb': [
    #     'static/src/xml/website_slides_share_link.xml',
    #     'static/src/xml/portal_chatter.xml',
    # ],

    'application': True,
    "external_dependencies": {
        "python": [
            "pytube",
            "pandas",
        ]
    },
}
