from . import slide_channel
from . import slide_slide
from . import res_country_town
from . import res_country_city
from . import res_partner
from . import res_users
from . import website_document
from . import website_blog
from . import ir_http
from . import azul
from . import help_center
from . import res_config_settings
from . import website_page
from . import event
from . import survey_user
from . import badge
from . import res_users_import
